For HG00100:
Read in WGS data...
done

Evaluate genotype originally called from ATAC-seq reads...
Read in genotype data called from ATAC-seq reads...
Traceback (most recent call last):
  File "Evaluation_metrics_combined.py", line 102, in <module>
    compute_genotype_metrics_called_and_imputed(sample, restrict_to_SNP = True)
  File "Evaluation_metrics_combined.py", line 25, in compute_genotype_metrics_called_and_imputed
    orginally_called = obtain_atac_variants_df(sample, WGS_result=WGS_df, restrict_to_SNP=restrict_to_SNP, Imputed = False, return_metric = False)
  File "/work-zfs/abattle4/heyuan/Variant_calling/benchmarking/Evaluation_metrics.py", line 53, in obtain_atac_variants_df
    SNP_called = pd.read_csv(SNP_called_fn, comment="$", sep='\t', nrows = 10)
  File "/home-4/yhe23@jhu.edu/.local/lib/python2.7/site-packages/pandas/io/parsers.py", line 678, in parser_f
    return _read(filepath_or_buffer, kwds)
  File "/home-4/yhe23@jhu.edu/.local/lib/python2.7/site-packages/pandas/io/parsers.py", line 440, in _read
    parser = TextFileReader(filepath_or_buffer, **kwds)
  File "/home-4/yhe23@jhu.edu/.local/lib/python2.7/site-packages/pandas/io/parsers.py", line 787, in __init__
    self._make_engine(self.engine)
  File "/home-4/yhe23@jhu.edu/.local/lib/python2.7/site-packages/pandas/io/parsers.py", line 1014, in _make_engine
    self._engine = CParserWrapper(self.f, **self.options)
  File "/home-4/yhe23@jhu.edu/.local/lib/python2.7/site-packages/pandas/io/parsers.py", line 1708, in __init__
    self._reader = parsers.TextReader(src, **kwds)
  File "pandas/_libs/parsers.pyx", line 384, in pandas._libs.parsers.TextReader.__cinit__
  File "pandas/_libs/parsers.pyx", line 695, in pandas._libs.parsers.TextReader._setup_parser_source
IOError: File /work-zfs/abattle4/heyuan/Variant_calling/datasets/GBR/ATAC_seq/alignment_bowtie/Called_GT/minDP2/HG00100.filtered.genotype.minDP2.txt does not exist
