For HG00136:
Read in WGS data...
done

Evaluate genotype originally called from ATAC-seq reads...
Read in genotype data called from ATAC-seq reads...
done

Measure performance...
Among all variants
Among 5977942 variants identified by WGS, 1741584 (0.291) are called by ATAC-seq reads, 1312296 (0.220) are correct
Among tested variants
[0.998296343640491, 0.2545430256093053, 0.9295576365570317, 0.7423431425893027, 0.9886769117040786, 0.7027044782080861]
done

================================================

Evalutae genotype imputed
Read in genotype data called from ATAC-seq reads...
Traceback (most recent call last):
  File "Evaluation_metrics_combined.py", line 102, in <module>
    compute_genotype_metrics_called_and_imputed(sample, restrict_to_SNP = True)
  File "Evaluation_metrics_combined.py", line 29, in compute_genotype_metrics_called_and_imputed
    imputed = obtain_atac_variants_df(sample, WGS_result=WGS_df, restrict_to_SNP=restrict_to_SNP, Imputed = True, return_metric = False)
  File "/work-zfs/abattle4/heyuan/Variant_calling/benchmarking/Evaluation_metrics.py", line 71, in obtain_atac_variants_df
    SNP_called = SNP_called.iloc[np.where([len(x.split('/')[1]) == 1 for x in SNP_called['%s_called' % sample]])[0]]
IndexError: list index out of range
